---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-redis-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-redis-app
  template:
    metadata:
      labels:
        app: go-redis-app
    spec:
      containers:
      - name: go-redis-app
        image: poojani/my-go-app:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: REDIS_HOST
          value: redis-master
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_PASSWORD
          value: ""
        - name: REDIS_DB
          value: "0"
        - name: PORT
          value: "8080"
         


---
apiVersion: v1
kind: Service
metadata:
  name: go-redis-app-service
spec:
  selector:
    app: go-redis-app
  ports:
  - name: http
    port: 9090
    targetPort: 8080
  type: NodePort
